#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../../lib")

require 'undercover'
require 'benchmark'

cli = Undercover::CLI.new
result = 0

time = Benchmark.realtime do
  result = cli.run
end

puts "Undercover finished in #{time}ms"
exit result
